/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.sipsmea.panel;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sipsmea.database;
import utils.TableFunc;

/**
 *
 * @author karel
 */
public class TempatPKL extends javax.swing.JPanel {

    public Statement st; // memberikan statement perintah sql, select insert delete
    public ResultSet rs; // membaca data di dalam db, membaca record di db
    Connection cn = database.connectDb();

    /**
     * Creates new form TempatPKL
     */
    public TempatPKL() {
        initComponents();
        refreshTable();

        TableFunc.centeringRow(tbTempatPKL);
    }

    private void refreshTable() {
        try {
            DefaultTableModel m = (DefaultTableModel) tbTempatPKL.getModel();

            String q = "SELECT * FROM tempat_pkl";
            Statement s = cn.createStatement();
            ResultSet r = s.executeQuery(q);
            m.getDataVector().removeAllElements();
            while (r.next()) {
                String nama = r.getString("nama_tempat");
                int rating = r.getInt("rating");
                int dayaTampung = r.getInt("daya_tampung");
                int aksesJalan = r.getInt("akses_jalan");
                int peminat = r.getInt("peminat");
                int jarak = r.getInt("jarak");
                Object[] data = {nama, rating, dayaTampung, aksesJalan, peminat, jarak};
                m.addRow(data);
            }

        } catch (SQLException e) {
            System.out.println("error: " + e.getMessage());
        }
    }

    private void clearTextField() {
        txtNama.setText("");
        txtJarak.setText("");
        txtAksesJalan.setText("");
        txtDayaTampung.setText("");
        txtPeminat.setText("");
        txtRating.setText("");
    }

    private void isiFieldDariTabel(int selectedRow) {
        if (selectedRow != -1) { // Pastikan ada baris yang dipilih
            String namaTempat = tbTempatPKL.getValueAt(selectedRow, 0).toString();
            int rating = Integer.parseInt(tbTempatPKL.getValueAt(selectedRow, 1).toString());
            int dayaTampung = Integer.parseInt(tbTempatPKL.getValueAt(selectedRow, 2).toString());
            int aksesJalan = Integer.parseInt(tbTempatPKL.getValueAt(selectedRow, 3).toString());
            int peminat = Integer.parseInt(tbTempatPKL.getValueAt(selectedRow, 4).toString());
            int jarak = Integer.parseInt(tbTempatPKL.getValueAt(selectedRow, 5).toString());

            txtNama.setText(namaTempat);
            txtRating.setText(String.valueOf(rating));
            txtDayaTampung.setText(String.valueOf(dayaTampung));
            txtAksesJalan.setText(String.valueOf(aksesJalan));
            txtPeminat.setText(String.valueOf(peminat));
            txtJarak.setText(String.valueOf(jarak));
        } else {
            JOptionPane.showMessageDialog(null, "Pilih baris yang ingin diupdate.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void updateData() {
        try {
            String sql = "UPDATE tempat_pkl SET rating=?, daya_tampung=?, akses_jalan=?, "
                    + "peminat=?, jarak=? WHERE nama_tempat=?";
            PreparedStatement stmt = cn.prepareStatement(sql);

            stmt.setInt(1, Integer.parseInt(txtRating.getText()));
            stmt.setInt(2, Integer.parseInt(txtDayaTampung.getText()));
            stmt.setInt(3, Integer.parseInt(txtAksesJalan.getText()));
            stmt.setInt(4, Integer.parseInt(txtPeminat.getText()));
            stmt.setInt(5, Integer.parseInt(txtJarak.getText()));
            stmt.setString(6, txtNama.getText());

            int rowsUpdated = stmt.executeUpdate();
            stmt.close();

            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Data berhasil diperbarui.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                refreshTable();
            } else {
                JOptionPane.showMessageDialog(null, "Gagal memperbarui data.", "Gagal", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTempatPKL = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtRating = new javax.swing.JTextField();
        txtDayaTampung = new javax.swing.JTextField();
        txtAksesJalan = new javax.swing.JTextField();
        txtPeminat = new javax.swing.JTextField();
        txtJarak = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        btnClear = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 249, 244));

        jLabel1.setFont(new java.awt.Font("Liberation Sans Narrow", 1, 18)); // NOI18N
        jLabel1.setText("TEMPAT PKL");

        jLabel2.setText("Daftar Tempat Praktek Kerja Lapangan (PKL)");

        tbTempatPKL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "Rating", "Daya Tampung", "Akses Jalan", "Peminat", "Jarak"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTempatPKL.setRowHeight(35);
        tbTempatPKL.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tbTempatPKL.setShowGrid(true);
        tbTempatPKL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTempatPKLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTempatPKL);

        jLabel3.setText("Rating");

        jLabel4.setText("Daya Tampung");

        jLabel5.setText("Akses Jalan");

        jLabel6.setText("Peminat");

        jLabel7.setText("Jarak");

        btnTambah.setBackground(new java.awt.Color(0, 102, 51));
        btnTambah.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(153, 0, 153));
        btnUpdate.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });

        jLabel8.setText("Nama");

        btnClear.setBackground(new java.awt.Color(0, 153, 153));
        btnClear.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(148, 148, 148))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(229, 229, 229))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(txtNama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAksesJalan, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtJarak, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel6))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtDayaTampung, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(104, 104, 104)
                                                    .addComponent(jLabel3))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(txtPeminat, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))))))
                                .addGap(18, 18, 18)
                                .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJarak, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAksesJalan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDayaTampung, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPeminat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        clearTextField();
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        try {
            if (txtNama.getText().isEmpty() || txtRating.getText().isEmpty()
                    || txtDayaTampung.getText().isEmpty() || txtAksesJalan.getText().isEmpty()
                    || txtPeminat.getText().isEmpty() || txtJarak.getText().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Harap isi semua field input.", "Peringatan", JOptionPane.WARNING_MESSAGE);

            } else {
                String sql = "INSERT INTO tempat_pkl (nama_tempat, rating, daya_tampung, "
                        + "akses_jalan, peminat, jarak) VALUES (?, ?, ?, ?, ?, ?)";

                PreparedStatement stmt = cn.prepareStatement(sql);

                stmt.setString(1, txtNama.getText());
                stmt.setInt(2, Integer.parseInt(txtRating.getText()));
                stmt.setInt(3, Integer.parseInt(txtDayaTampung.getText()));
                stmt.setInt(4, Integer.parseInt(txtAksesJalan.getText()));
                stmt.setInt(5, Integer.parseInt(txtPeminat.getText()));
                stmt.setInt(6, Integer.parseInt(txtJarak.getText()));

                int rowsUpdated = stmt.executeUpdate();

                stmt.close();

                if (rowsUpdated > 0) {
                    JOptionPane.showMessageDialog(null, "Data tempat pkl berhasil ditambahkan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    clearTextField();
                    refreshTable();
                } else {
                    JOptionPane.showMessageDialog(null, "Gagal menambahkan data.", "Gagal", JOptionPane.ERROR_MESSAGE);
                    clearTextField();
                }
            }

        } catch (NumberFormatException e) {
            // Tangani jika input bukan angka (misalnya pada field Rating, Daya Tampung, dll.)
            JOptionPane.showMessageDialog(null, "Input tidak valid. Pastikan semua field berisi angka.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException e) {
            // Tangani kesalahan SQL jika terjadi
            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        updateData();
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void tbTempatPKLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTempatPKLMouseClicked
        int selectedRow = tbTempatPKL.getSelectedRow();
        isiFieldDariTabel(selectedRow);
    }//GEN-LAST:event_tbTempatPKLMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTempatPKL;
    private javax.swing.JTextField txtAksesJalan;
    private javax.swing.JTextField txtDayaTampung;
    private javax.swing.JTextField txtJarak;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPeminat;
    private javax.swing.JTextField txtRating;
    // End of variables declaration//GEN-END:variables
}
